site_name: OGS Documentation
site_url: https://haller-erne.github.io/ogs/
nav:
    - Home: index.md
    - Tool configuration:
        - Overview: tools/README.md
        - Remote Tool Gateway: 
            - Overview: tools/remote-tool.md
        - OpenProtocol tools: 
            - Overview: tools/openprotocol/README.md
            - Nexo/Nexo2: tools/openprotocol/nexo.md
            - CS351: tools/openprotocol/sys350-cs351.md
            - KE350: tools/openprotocol/sys350-ke350.md
            - OPEXplus:  tools/openprotocol/opexplus.md
            - GWK OP22/OP+: tools/openprotocol/gwk.md
            - Sturtevant 400mp/TCVe2: tools/openprotocol/sturtevant.md
            - AMT/EST SX Wifi tools: tools/openprotocol/amt.md
            - Cleco Wifi tools: tools/openprotocol/cleco.md
            - Makita Wifi tools: tools/openprotocol/makita.md
            - HS-Technik NutBee riveting tool: tools/openprotocol/hstechnik.md
        - Non-OpenProtocol tightening tools:
            - n-gineric: tools/openprotocol/ngineric.md
            - Doga BM-series: tools/doga-wifi.md
        - Misc tools:
            - OGS GUI input: tools/misc/gui-input.md
            - AIOI Pick2Light: tools/misc/aioi-pick2light.md
            - Gesipa riveting tool: tools/misc/gesipa-mqtt.md
            - Keyence IV4 AI Vision sensor: tools/misc/keyence-iv4.md
            - Sylvac Meters: tools/misc/sylvac.md
        - Positioning:
            - Overview: tools/positioning/README.md
            - ART SmartTrack/DTrack: tools/positioning/positioning-art-dtrack.md
            - ART Verpose: tools/positioning/positioning-art-verpose.md
    - Additional configuration:
        - Socket trays: tools/misc/socket-tray.md
        - Projector: tools/misc/projector.md
    - Data output:
        - End-of-process (XML) file: dataoutput/xmlfile.md
        - Printout and label printing: dataoutput/printout.md
        - Traceability: dataoutput/traceability.md
        - Event logging: dataoutput/eventlog.md
    - Scripting:
        - Getting Started: v3/getting-started.md
        - LUA interfaces:
            - Eventlog: v3/lua/eventlog.md
            - Web browsers: v3/lua/webbrowser.md
            - Webserver (and REST API): v3/lua/webserver.md
            - Bluetooth LE: v3/lua/bluetooth-le.md
        - LUA custom tools: v3/lua/customtools.md
    - LUA helper libraries:
        - ADS communication (TwinCat, Nexeed, Beckhoff): libs/lua-ads.md
        - OpcUA communication: libs/lua-opcua.md
        - Modbus/TCP/UDP communication: libs/lua-modbus.md
        - USB HID Devices (Buttons, Arduino, etc.): libs/lua-hid.md
        - Data Protection API (safe secrets storage): libs/lua-dpapi.md
        - LUA network helpers (REST/OpenAPI): libs/lua-net.md
    - Enterprise functionality:
        - Central/shared configuration database: appnotes/sharedconfig.md
        - Databanking and multi-station rework: appnotes/databanking.md
        - Central user administration: appnotes/userdb.md
        - Tool roaming and dynamic parameters: appnotes/toolgateway.md
        - Traceability: appnotes/traceability.md
    - Application notes:
        - Using BLE Gateways: appnotes/openmqttgateway.md
        - Debugging LUA Scripts: appnotes/debugging.md
        - Station IO: appnotes/station_io.md
    
# sample
#    – Version 1.x:
#        – Types:
#            – Comments: v1/types/comments.md
#            – Posts: v1/types/posts.md
#

#theme: readthedocs
theme: 
  name: material
  # Favicon and logo
  # favicon: path/to/file.png
  # logo: path/to/file.png
  features:
    - content.code.copy
    - content.code.annotate 
    - content.tabs.link
  icon:
    annotation: material/help-circle

extra_css:
  - css/neoteroi-mkdocs.css

plugins:
    - search
    - glightbox
    
markdown_extensions:
  - abbr
  - meta
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      anchorlink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.smartsymbols
  # see https://www.neoteroi.dev/mkdocs-plugins/spantable/
  - neoteroi.spantable
  