site_name: OGS Documentation
site_url: https://haller-erne.github.io/ogs/
nav:
    – Home: index.md
    – Scripting:
        – Getting Started: v3/getting-started.md
        – LUA interfaces:
            – Web browser: v3/lua/webbrowser.md
    - LUA helper libraries:
        - ADS communication (TwinCat, Nexeed, Beckhoff): libs/lua-ads.md
        - OpcUA communication: libs/lua-ads.md
        - Modbus/TCP/UDP communication: libs/lua-ads.md

# sample
#    – Version 1.x:
#        – Types:
#            – Comments: v1/types/comments.md
#            – Posts: v1/types/posts.md
#

theme: readthedocs