# This generates the documentation using mkdocs and publishes the results on the gh-deploy branch

name: Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files mkdocs-material mkdocs-material-extensions pymdown-extensions pygments mkdocs-glightbox neoteroi-mkdocs
#markdown-full-yaml-metadata==2.2.1
#markdown==3.3.7
#mkdocs-ezlinks-plugin==0.1.14
#mkdocs-git-revision-date-localized-plugin==1.1.0
#mkdocs-material-extensions==1.1.1
#mkdocs-redirects==1.2.0
#mkdocs==1.4.2
#mkdocs-static-i18n==0.53
#mkdocs-minify-plugin==0.6.2
#mkdocs-meta-descriptions-plugin==2.2.0
#mkdocs-glightbox      
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy

